// Code generated by Slice Machine. DO NOT EDIT.

import AboutImage from './AboutImage';
import AboutText from './AboutText';
import Bibliography from './Bibliography';
import Collections from './Collections';
import ContactInfo from './ContactInfo';
import Education from './Education';
import EnlargedSlider from './EnlargedSlider';
import Exhibitions from './Exhibitions';
import MainImage from './MainImage';
import Project from './Project';

export {
	AboutImage,
	AboutText,
	Bibliography,
	Collections,
	ContactInfo,
	Education,
	EnlargedSlider,
	Exhibitions,
	MainImage,
	Project,
};

export const components = {
	about_image: AboutImage,
	about_text: AboutText,
	bibliography: Bibliography,
	collections: Collections,
	about_info: ContactInfo,
	education: Education,
	enlarged_slider: EnlargedSlider,
	exhibitions: Exhibitions,
	main_image: MainImage,
	project: Project,
};
