// Code generated by Slice Machine. DO NOT EDIT.

import AboutImage from './AboutImage';
import AboutInfo from './AboutInfo';
import AboutText from './AboutText';
import EnlargedSlider from './EnlargedSlider';
import MainImage from './MainImage';
import Project from './Project';

export {
	AboutImage,
	AboutInfo,
	AboutText,
	EnlargedSlider,
	MainImage,
	Project,
};

export const components = {
	about_image: AboutImage,
	about_info: AboutInfo,
	about_text: AboutText,
	enlarged_slider: EnlargedSlider,
	main_image: MainImage,
	project: Project,
};
